
# name: Deploy Education CRM (Docker)

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       # Docker image ni GitHub Actions da build qilamiz (tez internet!)
#       - name: Build Docker image
#         run: docker build -t education-crm:latest .

#       # Image ni tar ga siqamiz
#       - name: Save image to tar
#         run: docker save education-crm:latest | gzip > crm-image.tar.gz

#       # Faqat image ni serverga yuboramiz — butun papka emas
#       - name: Copy image to VPS
#         uses: appleboy/scp-action@v0.1.7
#         with:
#           host: ${{ secrets.SERVER_IP }}
#           username: root
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           source: "crm-image.tar.gz,docker-compose.yml,.env"
#           target: "/var/www/education-crm"

#       # Serverda faqat image load + run — build yo'q!
#       - name: Deploy on VPS
#         uses: appleboy/ssh-action@v1.0.3
#         with:
#           host: ${{ secrets.SERVER_IP }}
#           username: root
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           command_timeout: 10m
#           script: |
#             cd /var/www/education-crm

#             # Eski containerni to'xtatish
#             docker compose down

#             # Yangi image ni load qilish
#             docker load < crm-image.tar.gz

#             # Ishga tushirish — --build YO'Q! (allaqachon build qilingan)
#             docker compose up -d

#             # Tozalash
#             docker image prune -f
#             rm -f crm-image.tar.gz


name: Deploy Education CRM (PM2)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy project to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/var/www/education-crm"

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 10m
          script: |
            cd /var/www/education-crm

            # Node modules o‘rnatish
            npm install

            # NestJS bo‘lsa build qilish
            npm run build

            # Agar pm2 yo‘q bo‘lsa o‘rnatish
            npm install -g pm2

            # Eski processni o‘chirish
            pm2 delete education-crm || true

            # Dist dan ishga tushirish
            pm2 start dist/main.js --name education-crm

            # PM2 ni saqlash
            pm2 save